<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcce7080f4d557f6749b9813646662bcb
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Sentiment\\' => 10,
        ),
        'C' => 
        array (
            'Cocur\\Slugify\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Sentiment\\' => 
        array (
            0 => __DIR__ . '/..' . '/davmixcool/php-sentiment-analyzer/src',
        ),
        'Cocur\\Slugify\\' => 
        array (
            0 => __DIR__ . '/..' . '/cocur/slugify/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcce7080f4d557f6749b9813646662bcb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcce7080f4d557f6749b9813646662bcb::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitcce7080f4d557f6749b9813646662bcb::$classMap;

        }, null, ClassLoader::class);
    }
}
