<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Sentiment\\' => array($vendorDir . '/davmixcool/php-sentiment-analyzer/src'),
    'Cocur\\Slugify\\' => array($vendorDir . '/cocur/slugify/src'),
);
